/* Generated by AN DISI Unibo */ 
package it.unibo.oprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Oprobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		
				var OWNER = "$name"; 
				var STEPSDONE=0;
				var N = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name request engage")
						request("engage", "engage($OWNER,350)" ,"basicrobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="inHome",cond=whenReply("engagedone"))
					transition(edgeName="t08",targetState="handleEngageRefused",cond=whenReply("engagerefused"))
				}	 
				state("handleEngageRefused") { //this:State
					action { //it:State
						CommUtils.outblack("engage $name refused")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("inHome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name - waiting in home...")
						forward("inhome", "inhome(0)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="execGetrp",cond=whenDispatch("getrp"))
					transition(edgeName="t010",targetState="execGetAsh",cond=whenDispatch("getash"))
				}	 
				state("execGetrp") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getrp(X,Y)"), Term.createTerm("getrp(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name - Moving to the WASTEIN PORT")
								delay(2000) 
								CommUtils.outgreen("$name - getting a rp")
								delay(2000) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="burninPort", cond=doswitch() )
				}	 
				state("execGetAsh") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("getash(X,Y)"), Term.createTerm("getash(X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outgreen("$name - Moving to the BORNOUT PORT")
								delay(2000) 
								CommUtils.outgreen("$name - extract ash")
								delay(2000) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="ashoutPort", cond=doswitch() )
				}	 
				state("burninPort") { //this:State
					action { //it:State
						CommUtils.outgreen("$name - Moving to the BURNIN PORT")
						delay(2000) 
						CommUtils.outgreen("$name - depositing a rp")
						delay(2000) 
						forward("endburnindeposit", "endburnindeposit(50)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t011",targetState="moveToHome",cond=whenDispatch("gohome"))
				}	 
				state("moveToHome") { //this:State
					action { //it:State
						CommUtils.outgreen("$name - Moving to HOME")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="inHome", cond=doswitch() )
				}	 
				state("ashoutPort") { //this:State
					action { //it:State
						CommUtils.outgreen("$name - Moving to the ASHOUT PORT")
						delay(2000) 
						CommUtils.outgreen("$name - depositing ash")
						delay(2000) 
						forward("endashdeposit", "endashdeposit(50)" ,"wis" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t012",targetState="moveToHome",cond=whenDispatch("gohome"))
					transition(edgeName="t013",targetState="execGetrp",cond=whenDispatch("getrp"))
				}	 
			}
		}
} 
