/* Generated by AN DISI Unibo */ 
package it.unibo.wis

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023

//User imports JAN2024

class Wis ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var ASHCONT=4;	//max 4 rp in ash storage (capacity)
				var RPCONT=0;
				var INCSTATUS=0; //0 libero, 1 occupato
				var INHOME=0; //0 in home, 1 non in home
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name start")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkStatus", cond=doswitch() )
				}	 
				state("updateRPCont") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("rpInWaste(RPCOUNT)"), Term.createTerm("rpInWaste(RPCOUNT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 RPCONT = payloadArg(0).toInt()	 
								CommUtils.outmagenta("$name - Update RP counter")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkStatus", cond=doswitch() )
				}	 
				state("updateAshLevel") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("ashMeasurement(rpCount)"), Term.createTerm("ashMeasurement(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 ASHCONT = payloadArg(0).toInt()	 
								CommUtils.outmagenta("$name - Update Ash level")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkStatus", cond=doswitch() )
				}	 
				state("updateIncStatus") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("burning(START_TIME)"), Term.createTerm("burning(START_TIME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 INCSTATUS = 1	 
								CommUtils.outmagenta("$name - start incinerator, update status")
						}
						if( checkMsgContent( Term.createTerm("finishedBurning(TIME_ELAPSED)"), Term.createTerm("finishedBurning(TIME_ELAPSED)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 INCSTATUS = 0	 
								CommUtils.outmagenta("$name - finish incinerator, update status")
								forward("getash", "getash(X,Y)" ,"oprobot" ) 
								 INHOME = 1	 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkStatus", cond=doswitch() )
				}	 
				state("updateInHomeStatus") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("inhome(STATUS)"), Term.createTerm("inhome(STATUS)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 INHOME = payloadArg(0).toInt()	 
								CommUtils.outmagenta("$name - update in home status")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkStatus", cond=doswitch() )
				}	 
				state("checkStatus") { //this:State
					action { //it:State
						CommUtils.outcyan("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 
									if (RPCONT > 0 && ASHCONT != 0 && INCSTATUS == 0) {
						forward("getrp", "getrp(X,Y)" ,"oprobot" ) 
						 
										INHOME = 1
									} else if (INHOME != 0) {
						forward("gohome", "gohome(0,0)" ,"oprobot" ) 
						 
									}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="updateRPCont",cond=whenDispatch("rpInWaste"))
					transition(edgeName="t01",targetState="updateAshLevel",cond=whenDispatch("ashMeasurement"))
					transition(edgeName="t02",targetState="updateIncStatus",cond=whenEvent("burning"))
					transition(edgeName="t03",targetState="updateIncStatus",cond=whenEvent("finishedBurning"))
					transition(edgeName="t04",targetState="checkStatus",cond=whenDispatch("endburnindeposit"))
					transition(edgeName="t05",targetState="checkStatus",cond=whenDispatch("endashdeposit"))
					transition(edgeName="t06",targetState="updateInHomeStatus",cond=whenDispatch("inhome"))
				}	 
			}
		}
} 
